from src.infrastructure.repositories.CentroRepository import CentroRepository
from src.infrastructure.repositories.CentroInscricoesRepository import CentroInscricoesRepository

from src.application.useCases.CentroUseCase import CentroUseCase
from src.application.useCases.CentroInscricaoUseCase import CentroInscricoesUseCase

from database import SessionLocal
databaseSessionGenerator = SessionLocal

centroRepository = CentroRepository(databaseSessionGenerator)
centroInscricoesRepository = CentroInscricoesRepository(databaseSessionGenerator)

centroUseCase = CentroUseCase(centroRepository=centroRepository, centroInscricoesRepository=centroInscricoesRepository)
centroInscricoesUseCase = CentroInscricoesUseCase(centroInscricoesRepository=centroInscricoesRepository)
